#!/bin/sh

urlregex='(((http|https|gopher|gemini|ftp|ftps|git)://|www\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)'
magnetregex='(magnet:\\?xt=urn:btih:[a-zA-Z0-9]*)'
zathuraregex='((zathura|pdf):[0-9]*[:]?[a-zA-Z0-9\(\)\+>.,/@$&%?$\#=_~-]*)'

urls="$(sed 's/.*│//g' |                               # remove mutt sidebars
    awk 'NF{printf "%s", $0; next} {print ""}' |       # remove linebreaks on non-empty lines (NF true only for non-emty lines)
    sed -re 's/(\s)*(> )(\s)*//g' |                    # handle possible line break (in `neovim`, see `showbreak`)
    grep -aEo "$urlregex|$magnetregex|$zathuraregex" | # grep only URIs as defined above
    uniq | sed -E 's/(\.|,|;|!|\?)$//g' |              # ignore neighboring duplicates and remove trailing punctuation
    sed 's|^www\.|https://www\.|g')"                   # xdg-open will not detect url without https://

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do case "${o}" in
    h) printf "Optional arguments for custom use:\\n  -c: copy\\n  -o: xdg-open\\n  -h: Show this message\\n" && exit 1 ;;
    o) # chosen="$(echo "$urls" | dmenu -i -p 'Follow URL: ' -l 10)"
        chosen="$(echo "$urls" | fmenu -g 100x15 -p 'Follow URI:' -m)"
        for uri in $chosen; do setsid xdg-open "$uri" >/dev/null 2>&1 & done ;;
    c) echo "$urls" | fmenu -g 100x15 -p 'Copy URI:' | tr -d '\n' | xsel -b ;;
    *) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done
